# Generated by Django 5.2.6 on 2025-09-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "member_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
