# Generated by Django 5.2.6 on 2025-09-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_managers_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="firebase_token",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
