# Generated by Django 5.2.6 on 2025-09-13 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0001_initial"),
        ("transaction", "0003_transaction_account_reference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingsaccount",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="savings_account",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="savingsaccount",
            name="saving_id",
        ),
        migrations.RemoveField(
            model_name="savingscontribution",
            name="contribution_id",
        ),
        migrations.AddField(
            model_name="savingsaccount",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="savingscontribution",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="savingscontribution",
            name="transaction_id_b2b",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="b2b_contributions",
                to="transaction.transaction",
            ),
        ),
        migrations.AddField(
            model_name="savingscontribution",
            name="transaction_id_c2b",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="c2b_contributions",
                to="transaction.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="savingsaccount",
            name="interest_incurred",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="savingsaccount",
            name="member_account_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="savingscontribution",
            name="saving",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to="savings.savingsaccount",
            ),
        ),
        migrations.DeleteModel(
            name="Member",
        ),
    ]
