# Generated by Django 5.2.6 on 2025-09-15 08:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0003_savingscontribution_member"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="savingsaccount",
            unique_together={("member",)},
        ),
    ]
