# Generated by Django 5.2.6 on 2025-09-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0004_alter_savingsaccount_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingscontribution",
            name="pension_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="savingscontribution",
            name="pension_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="savingscontribution",
            name="vsla_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
