# Generated by Django 5.2.6 on 2025-09-15 10:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0005_alter_savingscontribution_pension_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savingscontribution",
            name="member",
        ),
        migrations.RemoveField(
            model_name="savingscontribution",
            name="pension_percentage",
        ),
        migrations.RemoveField(
            model_name="savingscontribution",
            name="saving",
        ),
        migrations.AlterField(
            model_name="savingscontribution",
            name="contributed_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="savingscontribution",
            name="pension_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="savingscontribution",
            name="vsla_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
