# Generated by Django 5.2.6 on 2025-09-17 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0006_remove_savingscontribution_member_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="savingscontribution",
            name="member",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="savings_contributions",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="savingscontribution",
            name="saving",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to="savings.savingsaccount",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="savingsaccount",
            name="interest_incurred",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="savingsaccount",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="savings_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="savingsaccount",
            name="member_account_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
