# Generated by Django 5.2.6 on 2025-09-26 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0008_alter_savingsaccount_member"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingsaccount",
            name="member",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="savings_account",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
