# Generated by Django 5.2.6 on 2025-09-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VSLA_Account",
            fields=[
                ("vsla_id", models.AutoField(primary_key=True, serialize=False)),
                ("account_name", models.CharField(max_length=255)),
                (
                    "account_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
