# Generated by Django 5.2.6 on 2025-09-10 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("C2B", "Customer to Business"),
                            ("B2C", "Business to Customer"),
                            ("B2B", "Business to Business"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "amount_transacted",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("paybill_number", models.CharField(blank=True, max_length=30)),
                ("recipient_phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("loan_repayment", "Loan Repayment"),
                            ("savings", "Savings"),
                            ("loan_disbursement", "Loan Disbursement"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_transaction_status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                            ("processing", "Processing"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("callback_url", models.CharField(blank=True, max_length=225)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": "MANAGER"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manager_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": "MEMBER"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="member_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
