# Generated by Django 5.2.6 on 2025-09-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="checkout_request_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
