# Generated by Django 5.2.6 on 2025-09-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_transaction_checkout_request_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="account_reference",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
