# Generated by Django 5.2.6 on 2025-09-17 13:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "transaction",
            "0004_alter_transaction_options_transaction_description_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_GUARANTOR", "Pending Guarantor Approval"),
                            ("PENDING_MANAGER", "Pending Manager Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("DISBURSED", "Disbursed"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                (
                    "requested_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("emergency", "Emergency"),
                            ("personal", "Personal"),
                            ("business", "Business"),
                        ],
                        default="personal",
                        max_length=20,
                    ),
                ),
                ("loan_reason", models.CharField(max_length=255)),
                (
                    "total_loan_repaid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("timeline_months", models.IntegerField()),
                (
                    "frequency_of_payment",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("disbursed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("repayment_due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction_id_b2c",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disbursed_loans",
                        to="transaction.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guarantor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guarantor_name", models.CharField(max_length=100)),
                ("guarantor_phone_number", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Expired", "Expired"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guaranteed_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guarantors",
                        to="loans.loanaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanRepayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_amount_repaid",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "loan_repayment_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Overdue", "Overdue"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repayments",
                        to="loans.loanaccount",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loan_repayments",
                        to="transaction.transaction",
                    ),
                ),
            ],
        ),
    ]
