# Generated by Django 5.2.6 on 2025-09-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guarantor",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="loanaccount",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="loanrepayment",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
