# Generated by Django 5.2.6 on 2025-09-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_alter_guarantor_id_alter_loanaccount_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guarantor",
            old_name="id",
            new_name="guarantor_id",
        ),
        migrations.RenameField(
            model_name="loanaccount",
            old_name="id",
            new_name="loan_id",
        ),
        migrations.RenameField(
            model_name="loanrepayment",
            old_name="id",
            new_name="repayment_id",
        ),
    ]
