# Generated by Django 5.2.6 on 2025-09-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0003_rename_id_guarantor_guarantor_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guarantor",
            name="guarantor_id",
        ),
        migrations.RemoveField(
            model_name="loanaccount",
            name="loan_status",
        ),
        migrations.RemoveField(
            model_name="loanrepayment",
            name="repayment_id",
        ),
        migrations.AddField(
            model_name="guarantor",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="loanrepayment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="loanaccount",
            name="timeline_months",
            field=models.PositiveIntegerField(),
        ),
    ]
