# Generated by Django 5.2.6 on 2025-09-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0004_remove_guarantor_guarantor_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanaccount",
            name="loan_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_GUARANTOR", "Pending Guarantor Approval"),
                    ("PENDING_MANAGER", "Pending Manager Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("DISBURSED", "Disbursed"),
                    ("COMPLETED", "Completed"),
                    ("PAID", "Paid"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
