# Generated by Django 5.2.6 on 2025-09-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0005_loanaccount_loan_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanaccount",
            name="interest_rate",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
