# Generated by Django 5.2.6 on 2025-09-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0006_alter_loanaccount_interest_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loanaccount",
            name="transaction_id_b2c",
        ),
    ]
