# Generated by Django 5.2.6 on 2025-09-26 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0007_remove_loanaccount_transaction_id_b2c"),
        (
            "transaction",
            "0004_alter_transaction_options_transaction_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="loanaccount",
            name="transaction_id_b2c",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disbursed_loans",
                to="transaction.transaction",
            ),
        ),
    ]
