# Generated by Django 5.2.6 on 2025-09-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0008_loanaccount_transaction_id_b2c"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loanaccount",
            name="loan_type",
        ),
    ]
