# Generated by Django 5.2.6 on 2025-09-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0009_remove_loanaccount_loan_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanaccount",
            name="loan_reason",
            field=models.CharField(
                choices=[
                    ("emergency", "Emergency"),
                    ("personal", "Personal"),
                    ("business", "Business"),
                ],
                default="personal",
                max_length=20,
            ),
        ),
    ]
