# Generated by Django 5.2.6 on 2025-09-27 21:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="updated_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
