# Generated by Django 5.2.6 on 2025-09-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pension", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pension",
            name="status",
            field=models.CharField(
                choices=[("active", "active"), ("inactive", "inactive")], max_length=20
            ),
        ),
    ]
