# Generated by Django 5.2.6 on 2025-09-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pension", "0003_alter_pensionaccount_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pensionaccount",
            name="contribution_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="pensionaccount",
            name="is_opted_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pensionaccount",
            name="total_pension_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
