# Generated by Django 5.2.6 on 2025-09-15 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pension", "0004_alter_pensionaccount_contribution_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pensionaccount",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected pension provider for B2B transfers",
                limit_choices_to={"status": "active"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pension.pension",
            ),
        ),
    ]
