# Generated by Django 5.2.6 on 2025-09-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pension", "0006_rename_pension_pension_provider"),
        (
            "transaction",
            "0004_alter_transaction_options_transaction_description_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pension_provider",
            new_name="PensionProvider",
        ),
    ]
